from typing import Union
from appaveli_codemind.core.models import AnalysisResult
from datetime import datetime
import json
import markdownify
import html

class ReportExporter:
    """Export analysis results to multiple formats (Markdown, HTML, JSON)"""

    @staticmethod
    def to_markdown(result: AnalysisResult) -> str:
        lines = [
            f"# 📊 Analysis Report for `{result.file_path}`",
            f"**Language:** {result.language.value.title()}",
            f"**Lines of code:** {result.line_count}",
            f"**Analysis time:** {result.analysis_timestamp.strftime('%Y-%m-%d %H:%M:%S')}",
            "",
        ]

        if result.security_issues:
            lines.append(f"## 🚨 Security Issues ({len(result.security_issues)})")
            for issue in result.security_issues:
                lines.append(f"### 🔒 {issue.type} (Line {issue.line})")
                lines.append(f"**Severity:** `{issue.severity.value.upper()}`")
                lines.append(f"> {issue.description}")
                lines.append(f"💡 **Fix**: {issue.fix_suggestion}\n")
        else:
            lines.append("✅ No security issues found.")

        if result.code_suggestions:
            lines.append(f"\n## 💡 Code Suggestions ({len(result.code_suggestions)})")
            for suggestion in result.code_suggestions:
                lines.append(f"### ✨ {suggestion.type.title()} (Line {suggestion.line})")
                lines.append(f"> {suggestion.description}\n")

        lines.append("\n---\nGenerated by [Appaveli CodeMind](https://github.com/appaveli/appaveli-codemind)")
        return "\n".join(lines)

    @staticmethod
    def to_html(result: AnalysisResult) -> str:
        markdown = ReportExporter.to_markdown(result)
        return markdownify.markdownify(markdown, heading_style="ATX")

    @staticmethod
    def to_json(result: AnalysisResult) -> str:
        from dataclasses import asdict
        data = asdict(result)
        data['analysis_timestamp'] = result.analysis_timestamp.isoformat()
        return json.dumps(data, indent=2, default=str)

    @staticmethod
    def export(result: AnalysisResult, format: str = 'markdown') -> str:
        format = format.lower()
        if format == 'markdown':
            from reports.markdown_report_exporter import MarkdownReportExporter
            return MarkdownReportExporter.export(result)
        elif format == 'html':
            from reports.html_report_exporter import HtmlReportExporter
            return HtmlReportExporter.export(result)
        elif format == 'json':
            return ReportExporter.to_json(result)
        else:
            raise ValueError("Unsupported format: " + format)
       
